### ISSUE TITLE
Raise timeout and client error exceptions

### ISSUE THREAD

**Issue by engrbm87** [home-assistant-libs/pydroid-ipcam#116]
I think we should raise the timeout and client error expectations [here](https://github.com/home-assistant-libs/pydroid-ipcam/blob/ed0e3f4128a530d8060e6054b465f4af5b6d75f8/pydroid_ipcam/__init__.py#L83) to be captured in the `android_ip_webcam` integration. This allows us to specify the kind of error (whether is it timeout or invalid credentials).

**Comment by MartinHjelmare** [comment]
Yes. Probably set `raise_for_status` and then raise library specific exceptions from the aiohttp exceptions.
