### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by Rj19God** [home-assistant-libs/pydroid-ipcam#186]
I wanted to make a program  or something like that which can go screen search and image recognition and after that write it on file. 
Actually it is for a game in which we scroll and search things it's a 800x800 map as each block have it's on coordinates so if the bot find the thing it could write that coords in file so I can check it later. 
Can I do all these on pydroid? 

I'm new and trying to learn so even a small advice will be help.

**Comment by MartinHjelmare** [comment]
From the Readme of this library:

> A Python asyncio library for interacting with the [IP Webcam](https://play.google.com/store/apps/details?id=com.pas.webcam) app that allows to use the built-in camera of Android phones as IP camera.
